FROM node:22-alpine as builder
WORKDIR /app


COPY package.json .
# Copy the startup script into the image
COPY package-lock.json .
COPY packages ./packages
COPY apps ./apps
COPY turbo.json .

RUN npm install --force --frozen-lockfile --verbose --no-audit --ignore-scripts

WORKDIR /packages/ui
RUN npm install --force --frozen-lockfile --verbose --no-audit --ignore-scripts
WORKDIR /app

WORKDIR /app/apps/web
RUN npm install --force --frozen-lockfile --verbose --no-audit --ignore-scripts
RUN npm run build

FROM node:22-alpine as production
WORKDIR /app

COPY --from=builder /app/apps/web/package.json .
COPY --from=builder /app/apps/web/next.config.mjs .
COPY --from=builder /app/apps/web/public ./public
COPY --from=builder /app/apps/web/.next/standalone/node_modules ./node_modules
COPY --from=builder /app/apps/web/.next/standalone/apps/web/server.js ./server.js
COPY --from=builder /app/apps/web/.next/standalone/apps/web/.next ./.next
COPY --from=builder /app/apps/web/.next/static ./.next/static

# Set the script as the default command to run on container start
CMD ["node", "server.js"]

EXPOSE 3000
